//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceReadCard.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AttendanceReadCard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;CardPositionSetting&gt;
        ///  &lt;!--2017/11/1，穎驊註解， 此份xml 為紀載點名卡的設定以便未來能夠提供不同學校的讀卡設定，本例為葳格高級中學2017/11 的版本  --&gt;
        ///  &lt;!--PerRowCount 代表有幾行、PerColumncount代表有幾列  --&gt;
        ///  &lt;!--StartPosition 代表其資料的起始點，Count代表往右數幾格，TotalRow 代表總共有幾列 ，Peroids 內容為卡片上的節次資訊 --&gt;
        ///  &lt;!--在程式碼內設定中斷點，實際執行看看，會更清楚讀卡的運作，(基本上就是數格子，可詳見ReadMe 資料夾內說明) --&gt;
        ///    &lt;AttendanceCardData&gt;      
        ///      &lt;PerRowCount&gt;35&lt;/PerRowCount&gt;
        ///      &lt;PerColumncount&gt;65&lt;/PerColumncount&gt;      
        ///      &lt;Grade&gt;      
        ///        &lt;StartPosition&gt;4&lt;/StartPosition&gt;
        ///        &lt;Count&gt;3&lt;/Count [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string CardPositionSettingData {
            get {
                return ResourceManager.GetString("CardPositionSettingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap ReadCard {
            get {
                object obj = ResourceManager.GetObject("ReadCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap sandglass_unlock_64 {
            get {
                object obj = ResourceManager.GetObject("sandglass_unlock_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
